#!/bin/bash

REV="$1"

GITDIR="$(git rev-parse --git-common-dir)"

COVERFILE="$(mktemp --suffix=.eml)"
git format-series "$REV" | sed 's/\s*$//' > "$COVERFILE"

REVIEWFILE="$GITDIR/reviews/$REV.md"
mkdir -p "$(dirname "$REVIEWFILE")"
if ! test -f "$REVIEWFILE"; then
    echo "# Review notes for $REV" > "$REVIEWFILE"
fi

commit_urls () {
    git rev-list "$REV:base..$REV:series" | sed "s@^@fugitive://$GITDIR//@" | tac
}

QFLISTFILE="$(mktemp)"
{ echo "$COVERFILE"; echo "$REVIEWFILE"; commit_urls; } >> "$QFLISTFILE"

vim -c"set errorformat=%f" -c"cfile $QFLISTFILE" -c"copen"
